### ISSUE TITLE
Nemo - In 'Properties' for a folder, when the folder name is highlighted, after changing the folder icon, typing will not change the folder name despite being highlighted unless you press 'Tab' once

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#100]
(tested on both a live session of Cinnamon as well as fully-updated local installations of both Cinnamon and Xfce as of 2022-07-15; could not test on a live session of Xfce due to issue #101)

**Describe the bug**
In Nemo, in 'Properties' for a folder, when the name is highlighted, after changing the folder icon, typing will not change the folder name despite being highlighted unless you press the 'Tab' key once.

**To Reproduce**
1. boot a copy of Mint 21 Cinnamon (whether a live session of a local installation) or Xfce (local installation only due to issue #101)
2. open Nemo (on Xfce this requires you to first install Nemo of course)
3. create a new folder
4. right-click on that newly-created folder and select 'Properties'
5. note how the folder name is highlighted; without doing anything else, click on the folder icon
6. choose a different icon and click the 'Select' button
7. note how the folder name is still highlighted, yet typing does not change the folder name
8. press the 'Tab' key once
9. now you can successfully type a different folder name

**Expected behavior**
After step 6, there are two possibilities on what would be expected to occur:
- the folder name is not highlighted
- the folder name _is_ highlighted and typing something will change the folder name

**Additional context**
This behavior also occurs if you create a folder on the desktop directly, but step two makes it applicable to other DE's as well such as Xfce (assuming you've previously installed Nemo of course).

**Comment by orcus-de** [comment]
It sounds like... you clicked the icon (button) to change the icon used; this switches the focus to the button.
To check if the icon (button) has focus after using it: Press the spacebar or enter key to show the icon selection dialog again.
Which agrees with your other "observation": Pressing the tab key... sets the focus to the next active/activated GUI element - which in your case is just the edit box.

And in case you're "surprised" that the selected text is still highlighted:
 As long as no other text editing element (within the same group of controls) is used to select text there instead, this is expected behavior (at least for me) - to keep the current selection == be able to use/click- on other GUI elements (like buttons, menu items, context menu items) to only perform operations on that selection (e.g. copy and paste menu items)
***
NintendoManiac64 - unrelated to the bug report: you might check if using a different theme would give you better visual feedback for the current/selected GUI element (might help in the future).

**Comment by NintendoManiac64** [comment]
I think what might be throwing me off is that text selection seems to be visually identical whether it is the currently-active highlighted text or it is "inactive" highlighted text.

**Comment by clefebvre** [comment]
We could force focus after the icon is switched (that's in nemo)... or improve the theme itself to make the visual distinction better. Either way things are acting as they're designed here, this isn't a regression in the scope of the BETA.
