### ISSUE TITLE
xfce4-panel: Adding apps to panel adds the wrong apps

### ISSUE THREAD

**Issue by clatterfordslim** [linuxmint/mint21-beta#131]
Since the release of Vanessa Beta Xfce Edition and with the disappearing panel bug, that had gotten moved over from Uma and Una.
I had also noticed a weird bug when adding Thunar or any other Icon to panel, either through Whiskermenu or adding the actual app from applications in .local file. or from filesystem /usr/share/applications. This actually goes right back to 16.04, maybe 14.04, or earlier? The reason why I'm writing is because this week I installed every single Xfce from 16.04 to Vanessa in VirtualBox, made a video of my findings.
https://www.youtube.com/watch?v=IL2WvJRTYJA

I believe this bug dates back even further and I do understand that getting a new release out is easier to release that new release by building upon the previous release using it as a template. The problem is though, is the regressions getting passed over to the new release and I understand that Cinnamon is your baby and your main OS, but I was shocked to see so many of the same bugs through out the different releases of Linux Mint Xfce. In my opinion and you can tell me to do one and go away if you want? I truly believe you should start from scratch with Vanessa Beta Xfce, using Xubuntu 22.04 as your base and remove everything you do not need. This way surely would remove any passed on bugs, that have occurred through out Linux Mint Xfce.

I must stress that I have been using Linux Mint through out the 20.04 series and back in 12.04 Maya the Mate edition, which I used to take around with me on a external hard drive to Libraries and other Internet Cafe's. Been using Linux since the end of 2009. Seen a lot happen over the years with Linux. I'm not a programmer in any way, shape, or form, but I do know how to build my own OS, just making the ISO I have problems with. I'm willing to help, as that is what Linux is all about community and helping one another, that's what this Forum is all about. I love Linux Mint especially Xfce and if you need help setting up Vanessa from scratch through Xubuntu 22.04, then please just ask? I did not know how else to show you my findings, other than putting it in a video and I know the video is long. Just hope I get my message across to you though?

Many Thanks
clatterfordslim

**Comment by clefebvre** [comment]
Hi,

There are some differences affecting the desktop between Xubuntu and Mint Xfce, the whisker menu, the default panel launchers etc (these might be at play here).. but more importantly what matters a lot here are the versions of the Xfce components. The bugs you describe take their root in Xfce. They might get fixed over time and the solution might simply be to backport a newer version or backport a fix into Linux Mint.

Anyway, let's focus on the bug you describe here. If I'm understand this correctly, we reproduce it like this:

- 1. Create panel 2
- 2. Add Thunar to panel 2, using the menu 
- 3. Repeat step 2 multiple times

When I do this in Mint 21 Xfce BETA I get three thunar launchers:

![image](https://user-images.githubusercontent.com/1138515/180429656-749438b0-b318-4261-ae1d-36dbb4216ad0.png)

This looks OK to me. Am I doing it wrong?

I tested this in live mode.

**Comment by clefebvre** [comment]
Ok, I understand this issue a little bit more.

- We don't need panel 2 at all. This can be reproduced with panel 1.
- It only happens as long as some of the initial panel launchers are removed (terminal, firefox, thunar).

To reproduce:

- Remove a panel launcher (say thunar)
- Add any app to the panel
- The removed launcher (thunar) is re-added instead of the app

Once the removed launchers are all mistakenly re-added, adding to the panel behaves correctly.

I had a look at the issues on the xfce4-panel project but couldn't find any issue that looked like this one.

I'd therefore suggest to open a bug report there @clatterfordslim : https://gitlab.xfce.org/xfce/xfce4-panel/-/issues

Here's some info about our launchers in case it's relevant. They are defined in /usr/share/mint-artwork/xfce/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml. I'm adding a copy of the file below.

[xfce4-panel.xml.zip](https://github.com/linuxmint/mint21-beta/files/9167469/xfce4-panel.xml.zip)
.

**Comment by clefebvre** [comment]
Note: It also happens with all packages updated from xubuntu-dev/staging.

If this gets fixed upstream in Xfce we can then consider backporting the new version, unless it's also planned for inclusion in Ubuntu.
