### ISSUE TITLE
Release notes: Grub "out of memory"

### ISSUE THREAD

**Issue by markushub** [linuxmint/mint21-beta#152]
ACPI Bios Error: Could not resolve symbol [/_SB.PC00.I2C2.TPL1], AE_NOT_FOUND 
    Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
    CPU: 2 PID: 1 Comm: swapper/0 Not tainted 5.15.0-39_generic #42-Ubuntu
    Hardware name: LG Electronics 16Z90P BIOS T22F0350 X64 07/22/2021

Booting with live image not possible

**Comment by dave-sarif** [comment]
Same issue:

**Describe the bug**
Unable to boot Mint 21 installer. 
1. Grub loads.
2. Select normal boot, or compatible boot.  Doesn't matter
3. Immediate "Error: out or memory"  error (screenshots below)


**To Reproduce**
Boot from USB or CD.
Boot normal or 'compatibility' 
No difference on any combination

**Expected behavior**
Boot without error

**Screenshots**
Screens attached of the boot process, error,  and kernel panic
hardware info also attached

**Additional context**
Able to boot Windows and Fedora 35 and Fedora 36 without issue

[hwinfo.txt](https://github.com/linuxmint/mint21-beta/files/9176812/hwinfo.txt)
![1-GrubScreen](https://user-images.githubusercontent.com/109925048/180667777-3ef9e464-c0f2-4922-96fd-f705b6ac241d.jpg)
![2-OutofMemory](https://user-images.githubusercontent.com/109925048/180667779-352edcba-09fe-46b2-9057-7e249ce787d3.jpg)
![3-Kernel-Panic](https://user-images.githubusercontent.com/109925048/180667784-cc307a30-4816-46c2-9d52-b58242ff4dc0.jpg)

**Comment by clefebvre** [comment]
It looks like it's a known issue upstream: 

https://askubuntu.com/questions/1404415/ubuntu-22-04-live-usb-fails-reports-out-of-memory-with-no-details-even-after
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1842320

The workaround is to use Rufus.

On our side we'll need to update the release notes to document this issue and workaround.
