### ISSUE TITLE
[Cinnamon] non-resizable windows have artifacts in rounded corners and missing 1px border

### ISSUE THREAD

**Issue by PicoMitchell** [linuxmint/mint21-beta#32]
Similar to https://github.com/linuxmint/mint20.3-beta/issues/26 but maybe not the same cause, some Java apps windows still seem to have artifacts in the rounded windows corners (screenshot attached). Was hoping the Mutter rebase would fix this, but maybe Java app windows are still being drawn a different way.

This can be seen with the Java TreeView app by installing `apt install treeview`. Oddly the main TreeView window does not have the artifacts, but the initial Registration windows does, as well as the About window.

Also, I just noticed this same issue on the Cinnamon File Copy progress window (screenshot attached). Not sure if that's a Java window (assuming it's not) or what is going on there.

![mint21-cinnamon-beta-rounded-corner-artifacts](https://user-images.githubusercontent.com/7358089/179117257-6d3ffc56-44c5-4e0f-9020-d5ce36291c7c.png)

![mint21-cinnamon-beta-preparing-copy-corner-artifacts](https://user-images.githubusercontent.com/7358089/179117262-4284efb7-f16c-4b7d-9bbd-b5ce6d3a0e40.png)

**Comment by PicoMitchell** [comment]
These windows in question appear to also not have the same darker 1px border that other windows have. Maybe that is part of the issue.

**Comment by PicoMitchell** [comment]
The Shut Down prompt as well a Delete confirmation and Empty Trash confirmation also has the issue of no 1px dark window border and artifacts on the rounded corners. It appears that many dialog prompt style windows throughout the system has this issue.

**Comment by PicoMitchell** [comment]
Oh shoot, this is a dupe of https://github.com/linuxmint/mint21-beta/issues/27. My bad!

**Comment by JosephMcc** [comment]
This should be the same fix as https://github.com/linuxmint/mint21-beta/issues/27

**Comment by PicoMitchell** [comment]
Makes sense, being a Java window was a red herring. The widows in question were all non-resizable windows as described in the commit for the fix in Muffin: https://github.com/linuxmint/muffin/commit/34c8a701ec46b7da7310095be5e5da56933d45f1

**Comment by PicoMitchell** [comment]
I'm now seeing a proper 1px border around non-resizable windows after updating to Muffin 5.4.2.

But, maybe there are other issues (which I haven't seen myself yet)? https://github.com/linuxmint/mint21-beta/issues/27#issuecomment-1186349453 (should that be added as a new/separate issue?)

**Comment by PicoMitchell** [comment]
I actually am seeing the light background squared corner issue consistently on shutdown confirmation prompt along with this flickering shadow issue: https://github.com/linuxmint/mint21-beta/issues/35

**Comment by SebastJava** [comment]
Well, i was trying to remember i should avoid invading other people's issues, and open my own instead. But now, here, you specifically asked for it. :) It's late, I'm tired, so i went the wrong way and packed 2 or 3 issues in one video. Because it all happened there in 60 seconds... Too much going on at the same time... I'll still try to sort this out.

I saw all these on VM, but this VM _"throws in another variable"_ (—JosephMcc), so, to confirm, i quickly reproduced a couple of things on a live USB stick. Real, not virtual. Of course, i am required to have an up-to-date system for this. I think i managed to do so, on live USB.

**To reproduce**
1. Start a live session on USB stick (USB 2.0 !)
2. Apply all system updates.
3. Prompted to reboot, but i can't do that, so i just logout/login. (The kernel is not updated that way, but everything else is, right?)
4. Then i did and i saw the things in the video below. We are talking about subtle details, so **please play this video full screen (1920x1080px).**

https://user-images.githubusercontent.com/31940713/179642496-2c4dd8d2-cf48-43f9-ad6d-27957e205678.mp4

_That's a MKV format video converted into MP4 for GitHub. It may have lost some accuracy in the process. And the video recording interfered with the "flashing" bug. In fact, the flashing is 10 times faster and uglier when there is no video capture process..._

**Video summary:**
1. Click on Update Manager refresh to confirm it is all up-to-date (as of 18 Jul 2022 21:00 -0400)
2. See error window. More info: bug #112
3. This error window also has some weird approx. squared shadows
4.  Menu > Shutdown dialog box: flashing issue #35 
5. Same Shutdown dialog box: subtle square light gray rectangle behind those round corners, https://github.com/linuxmint/mint21-beta/issues/27#issuecomment-1186349453

![square-shadows-2X-2022-07-18-21-00](https://user-images.githubusercontent.com/31940713/179646067-fceb108e-1460-4035-8fbc-ed40ab0a4819.jpg)
_Subtle square light gray rectangle behind those round corners (screenshot from video, 2X scale)_


NOTE: Those kind of square shadows go away as soon as you try to move the window. AND you can't get this into a screenshot, that's why i had to make this video, which then brought back all these other issues !..

As i already said, i saw these on both VM and live USB.
[liveUSB-inxi.txt](https://github.com/linuxmint/mint21-beta/files/9136686/liveUSB-inxi.txt)
[VM-inxi.txt](https://github.com/linuxmint/mint21-beta/files/9136690/VM-inxi.txt)

P.S.: Maybe some of these are fake issues, i don't know, because it is not a real installation... That's live USB and, also, installed and up-to-date on VirtualBox +GAs...

**Comment by SebastJava** [comment]
> I actually am seeing the light background squared corner issue consistently on shutdown confirmation prompt along with this flickering shadow issue: https://github.com/linuxmint/mint21-beta/issues/35

— @PicoMitchell 

Okay, so i am not the only one seeing these subtle issues. But what kind of LinuxMint 21 are you looking at? Live USB? or better, installed on VirtualBox +GAs, all up-to-date, or... the real thing, a real installation on real HDD or SSD, and all up-to-date ?
Please type `inxi -Fxxxrz` in your terminal and copy-paste the output here. Or, better, type `inxi -Fxxxrz > inxi.txt` and attach this **inxi.txt** text file to upload the same info but in a clean, de-cluttering way. Thanks.

**Comment by PicoMitchell** [comment]
Fully updated installation on real hardware. The computer is at work though, I'll post the command output tomorrow.

**Comment by SebastJava** [comment]
Excellent!

**Comment by SebastJava** [comment]
Sorry about this messy previous post here, the one packed with at least 3 different issues (https://github.com/linuxmint/mint21-beta/issues/32#issuecomment-1188506664)

So, to sum up, now we are talking again about https://github.com/linuxmint/mint21-beta/issues/27#issuecomment-1186349453 and #35.

**I will do an update on this.** Trying to keep it short and clear. I don't know if i should make it an update in #35, or a new issue about those "square shadows", those subtle light gray rectangles behind those Mint-Y rounded corners...

Or maybe @PicoMitchell  should open this half-new issue? He is more credible with his 100% real installation... Or else he could just confirm my new issue or update...

**Comment by SebastJava** [comment]
All done: #120
Open videos and pictures in a new tab, full screen or zoomed >= 100%
@PicoMitchell I would appreciate if you could just comment this #120 to say you confirm all this on a **real hardware,** installed, up-to-date LM21. Thanks.

**Comment by PicoMitchell** [comment]
Thanks so much for doing that! I will post in that new issue when I'm back at work.

**Comment by JosephMcc** [comment]
The shadow issue is a separate one from the original bug this was for. The 1px window border and the artifact on the rounded corner are fixed.
