### ISSUE TITLE
ubiquity: "Multimedia codecs" prompt screen appears with preseed that previously skipped all questions.

### ISSUE THREAD

**Issue by PicoMitchell** [linuxmint/mint21-beta#34]
The preseed I've been using for Mint 20.3 and many previous versions which would bypass all user prompts to do an automated installation (by using the `automatic-ubiquity` kernel argument)  is now prompting this "Multimedia codecs" screen (screenshot attached).

Here is the preseed I've been using: https://github.com/freegeek-pdx/Linux-Deployment-and-Support-Scripts/blob/main/Mint%20Installer%20Resources/preseed/production-ubiquity.seed

From the log (also visible in the screenshot), I was able to see that it's waiting for a `ubiquity/use_nonfree` value. So, I tried including `ubiquity ubiquity/use_nonfree true` in my preseed file and now the screen is bypassed properly.

So, this issue is resolved on my end, but I'm not sure if this is an intentional change to require this new preseed value that was not required before. I figured I would report this since it may trip up other users if not intentional or documented somewhere.

![IMG_2578](https://user-images.githubusercontent.com/7358089/179121624-da3b3e50-46ca-4a42-ad4e-0c5b629c078e.jpeg)

**Comment by clefebvre** [comment]
We don't really support preseeding in Linux Mint. This is an inherited feature from Ubuntu due to the fact that we use ubiquity.

I'd suggest testing this with Ubuntu 20.04 and 22.04 first to see if this is a regression on their side. If it is, then it should be reported on Launchpad against Ubiquity.

If Ubuntu fixes it and updates ubiquity in 22.04 we can rebase our version to include the fix.
