### ISSUE TITLE
live: Slow boot sequence

### ISSUE THREAD

**Issue by PicoMitchell** [linuxmint/mint21-beta#36]
I initially noticed my first USB live boot using the seemed quite a bit slower than previously, but I didn't bother timing it until I had things setup with my customized installation straight to Ubiquity.

Now, I did a time test of a network boot to Ubiquity on Mint 20.3, and it takes about 30 seconds to boot to the point that my custom scripts (via preseed `partman/early_command`) run (video linked).

On Mint 21 beta, the same hardware (with the same network conditions) takes **_2 minutes_** and 30 seconds to boot (video linked). You can see the actual boot process takes quite a bit longer, but it also takes much longer to even load the Ubiquity window where first the titlebar loads and then eventually the window contents. Both videos stop when other windows open over the Ubiquity progress window which are windows opened by my custom scripts.

Again, these tests are on a network boot to a customized Ubiquity installation. But, I experienced similar slowness on my initial USB live boot test with no customizations. If this issue is not easily reproducible for you, or you need other examples. I can do similar time testing with Live USBs of Mint 20.3 vs Mint 21 beta. But regardless, this slowness to networks boot to the installation environment will be an issue for us.

Also, whatever is going on here seems to be specific to Live Boots. The actual installed OS boot time after the installation is done is quick as expected.

[Mint 20.3 Live Boot (30 seconds)](https://apps.freegeek.org/mint21-beta-issue-attachments/mint20.3-live-boot.mov)

[Mint 21 Live Boot (**_2 minutes_** 30 seconds)](https://apps.freegeek.org/mint21-beta-issue-attachments/mint21beta-live-boot.mov)

**Comment by PicoMitchell** [comment]
It's also worth noting that the `fsck.mode=skip` boot argument is set for both the Mint 20.3 and Mint 21 network boots, so that filesystem check is not causing the slowness.

**Comment by PicoMitchell** [comment]
Here is the output of `systemd-analyze critical-chain` for both Mint 21 beta and Mint 20.3 when booting to the Cinnamon Live Boot sessions with unmodified USBs (since I can't run that command in the Ubiquity modes since it considers boot to not be finished).

It appears that `NetworkManager` and `NetworkManager-wait-online.service` are taking the longest on Mint 21 beta while those doesn't even show up on Mint 20.3. Not sure if that is the only culprit here or not since the entire boot process seems slower as can be seen in the videos.

Mint 21 beta:
![IMG_2596](https://user-images.githubusercontent.com/7358089/179321742-88297c26-037a-497d-a582-a1db7ba4659e.jpeg)

Mint 20.3:
![IMG_2597](https://user-images.githubusercontent.com/7358089/179321760-03cf8df1-fe48-4599-a17d-6264d7823f02.jpeg)

**Comment by PicoMitchell** [comment]
On another Mint 21 beta Live Boot, it appears these NetworkManager entries didn't even show up, and `blueman-mechanism.service` was the slowest. Odd.

![IMG_2598](https://user-images.githubusercontent.com/7358089/179323149-c848a5e6-7310-482e-b94a-49b871773590.jpeg)

**Comment by PicoMitchell** [comment]
Having these culprits gave me some more things to google, I found that I can stop some of these from loading on boot _as a test_ by using the following boot arguments: `systemd.mask=NetworkManager-wait-online.service systemd.mask=blueman-mechanism.service`

That seemed to help _maybe_ speed things up _a little_ (I can't really tell easily since it still takes over a minute and every boot time is not consistent), but still _much_ slower than Mint 20.3 which is always around 30 seconds. And, I don't know if it's really desirable/safe to disable these slow services arbitrarily. Hoping for some insight into what else may have changed to cause this slower live boot.

Also, when booting to my customized Ubiquity setup, I am still seeing a longer load time once the cursor appears (as seen in the first video).

**Comment by PicoMitchell** [comment]
Here is the output of `systems-analyze blame` for both Mint 21 beta and Mint 20.3 unmodified USB live boots to see how its a collection of a variety of services that are all just a bit slower on Mint 21.

I don't know enough about these service to know which ones would be safe to mask during boot for a faster boot time without losing necessary services. Also, it seems like undesirable behavior that these services take so much longer to load on Mint 21 beta than they did on Mint 20.3. Hopefully this info is helpful to find a solution, even if it's just a safe workaround so that we can get back to ~30 second network boot time to our custom installer.

Mint 21 beta:
![IMG_2602](https://user-images.githubusercontent.com/7358089/179324916-2135b3c6-3290-4b0e-8f9d-86b9fad7895f.jpeg)

Mint 20.3:
![IMG_2601](https://user-images.githubusercontent.com/7358089/179325313-563a9b82-2e11-4387-9ea2-9755d68dacd9.jpeg)

**Comment by Acheron17** [comment]
Here are the differences I am seeing on a live boot between Linux Mint Cinnamon 20.3 and 21.
Some difference but maybe its hardware related (this system does not have Bluetooth).  Its hard to pinpoint or find cause because Linux Mint relies on the stack from Ubuntu for the majority of services and behavior.

![lm203-systemd-analyze](https://user-images.githubusercontent.com/45599505/179354383-8845b4ab-2d27-41e6-a79f-bc1a712400fa.png)

![lm-210-systemd-analyze](https://user-images.githubusercontent.com/45599505/179354400-36eb7811-b4e8-455e-a66e-171f755e9308.png)

![lm203-systemd-analyze-blame](https://user-images.githubusercontent.com/45599505/179354410-55dfe18d-a8ef-4516-b980-1d7aa2f06356.png)

![lm210-systemd-analyze-blame](https://user-images.githubusercontent.com/45599505/179354502-3b03d1ee-1053-4614-9cdb-1905f27ea5a4.png)

**Comment by PicoMitchell** [comment]
Here is another slow live boot of Mint 21 from a different computer than my previous tests. This time including the output of `systemd-analyze` with no added argument as well.

![image](https://user-images.githubusercontent.com/7358089/179364583-3e9ed630-2ce3-480d-b738-8dba3e5c4153.jpeg)

**Comment by clefebvre** [comment]
As @Harry-W-Haines-III said, we inherit the 22.04 stack here. It's possible there's an actual bug at play. It's possible also that the boot sequence involves more than before. Either way, this isn't a bug yet since there's no identified fault or actual component to correct.

You're still in the troubleshooting phase. It's definitely slower but you don't know why yet.

Note: We'll update blueman to 2.3.1 before STABLE. This might help with blueman-mechanism. Plymouth got some updates between 20.04 and 22.04. Casper-md5check might run in the background whereas it didn't before, this would definitely impact the live boot speed. These are just leads though, there's no actual identified issue yet other than the observation that things are slower. I'll close this for now until we find an actual bug we can fix.
