### ISSUE TITLE
mate: tray icons look too big

### ISSUE THREAD

**Issue by tamajon** [linuxmint/mint21-beta#67]
I haven't found a way to change the size or theme of the system tray icons, in their current state they look too big and unsightly, breaking the elegance of Linux Mint. I have tried different methods but it has not been possible to customize the system tray, I am using Linux Mint 21 Beta Mate.

![lewa](https://user-images.githubusercontent.com/68070152/179360008-d2cd0404-ed82-4e67-9aa8-64a932203294.png)

**Comment by jsane-h8ms** [comment]
I also tried to change the symbolic tray icons back to the previous, non-symbolic versions of Mint 19.x.
It didn't work, the battery icon changed but looked corrupted. (Tried via custom icon theme).

I would love an option or any way to "turn off" symbolic icons and have the tray look just like older Mint versions.
(I'm kinda OCD about this, wasted a few hours trying with Mint 20 and kept my main workstations on Mint 19.3 because of this ;)

**Comment by clefebvre** [comment]
We might be able to do something about this. Afaik these are rendered by the xapp tray applet directly.

**Comment by clefebvre** [comment]
Fixed in xapp 2.2.14.
