### ISSUE TITLE
python3-grpcio (1.30.2-3build6) causes any app that uses it to consume 100% of the CPU.

### ISSUE THREAD

**Issue by gustavo-iniguez-goya** [linuxmint/mint21-beta#78]
**Describe the bug**
python3-grpcio (1.30.2-3build6) causes any app that uses it to consume 100% of the CPU.

**To Reproduce**
 
 0. sudo apt install python3-grpcio

 1. clone grpcio basic example ( http://grpc.io/docs/languages/python/basics/ )
     $ git clone -b v1.45.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc

 2. $ cd grpc/examples/python/route_guide

 3. on one terminal: $python3 route_guide_server.py
     Observe that **the script is taking up 100% of the CPU**

4. On another terminal launch the client and observe that it does nothing: $ python3 route_guide_client.py

**Expected behavior**
Apps, shouldn't use 100% CPU. It worked fine on previous LinuxMint versions.

**Additional context**

This error was already reported to the Ubuntu devs: https://bugs.launchpad.net/ubuntu/+source/grpc/+bug/1971114

Since LinuxMint 21 is based on Ubuntu 22.04, this bug is affecting now LinuxMint 21.

It also affets our project chttps://github.com/evilsocket/opensnitch/issues/647 , among others.

**Comment by mtwebster** [comment]
Hi, thanks - I'm the guy on that bug report who said 'me too'. We're working around this for Warpinator (the one app we have that uses python3-grpc) by bundling a working version with the app:  https://github.com/linuxmint/warpinator/commit/3f93efadbe77a46e570dbd8afc13d1593d40af35. We may continue doing that even once the Ubuntu package is fixed - no having to deal with this situation again.

Presumably Ubuntu will get a new version out (I would have thought by now), but otherwise this isn't really a beta issue.

**Comment by gustavo-iniguez-goya** [comment]
Thank you @mtwebster , it was more a FYI issue than a bug, I didn't know where to post it.

Just for the record, Debian Sid version 1.30.2-3+b5 doesn't suffer from this problem, and both Ubuntu and Debian packages have the same patches, so it seems a recompilation/link/whatever problem.

**Comment by Acheron17** [comment]
For issues like this it would be great to have a label "Upstream Workaround"

**Comment by mtwebster** [comment]
@gustavo-iniguez-goya I know, I appreciate it - I think the one big difference I noticed when troubleshooting this is that Debian (stable) is using python 3.9, we're using 3.10.
