### ISSUE TITLE
ubiquity: keyboard layout reset before user page

### ISSUE THREAD

**Issue by infozorro** [linuxmint/mint21-beta#88]
The local keyboard is defined during the very beginning of the installation.
But while setting the passwords, the keyboard is English only.
You cannot set a password with e.g. a German keyboard, because 'y' and 'z' are mixed, and more.

After installation everything is all-right, but not during.

(Thank for all your work, linux mint is beautiful. I hope that I opened this issue in a correct way.)

**Comment by SebastJava** [comment]
> I hope that I opened this issue in a correct way.

How did you install? Live USB stick ? Virtual Machine? Other?

**Hardware and mintUpdate**
* You could provide `inxi -Fxxxrz` output to describe your hardware and drivers
* Is your system all up-to-date ? Not yet, i suppose...

**Comment by SebastJava** [comment]
I had a similar issue. On VirtualBox, during install process. I could successfully select my keyboard layout on step 2, but then, later, when creating this user account, i couldn't write "Sébastien" with this "é" (french accent).

**Steps to reproduce the behavior:**
1. Start live virtual CD (VirtualBox here...) and launch Installer
2. At step 2, select "English (US, intl., with dead keys)" keyboard layout
3. At the final step, this "Who are you" step, try to write some name with french accent. Ex.: "Valérie"
4. See? You just can't type "é" (AltGr + E)

**Expected behavior**
I would have loved to be able to write "Valérie" with this french accent, otherwise it is not exactly the same name.

![VirtualBox_LinuxMint-21-Cinnamon-BETA-live-installer-keyboard](https://user-images.githubusercontent.com/31940713/179413154-9737875c-773c-49f1-9ec7-5101ec90180a.png)

![VirtualBox_LinuxMint-21-Cinnamon-BETA-live-installer-ID](https://user-images.githubusercontent.com/31940713/179413195-39c7a0a0-f2b4-478a-ab72-9b7adc776cfb.png)

**Hardware and mintUpdate**
* [inxi -Fxxxrz.txt](https://github.com/linuxmint/mint21-beta/files/9128191/inxi.-Fxxxrz.txt)
* Is your system all up-to-date ? No.

**Comment by infozorro** [comment]
How did I start:
- VMware Workstation for Linux 16.2.3 (latest version)
- Host in the Office: ubuntu Mate 20.04 (22.04 still does not run the VMware)
- Host at home: Mint Mate 20.3 
- Guest with Mint Mate 21 USB Stick, Language and Keyboard set to German
- Guest with Mint Cinnamon 21 USB Stick, same as above
What happened:
- The check of the keyboard was all-right. y and z were on the right position.
- While setting up the password, y and z and other characters had there American position again.
- After the install and restart, the German keyboard was perfectly available.
See inxi from my office-system below
![inxi_-Fxxxrz_screenshot_ 2022-07-18_13-38-02](https://user-images.githubusercontent.com/4319312/179509181-c1211064-c9bd-4c39-90b0-ce8303f51da2.png)

**Comment by infozorro** [comment]
sorry, the issue is not closed

**Comment by MenthaSuaveolens** [comment]
I can confirm this problem. Keyboard set to Belgian (= Azerty), but when typing in "Who are you", the layout is still Qwerty

**Comment by MenthaSuaveolens** [comment]
One can get around this problem by configuring the keyboard lay-out before installing.

Test1 : Start installation -> Set Keyboard-layout=azerty -> @ Who are you the layout = qwerty, installed system has the right layout= AZERTY

Test2 : Set keyboard-layout=azerty (English(US) removed) -> Start installer -> Set Keyboard-layout=azerty -> @ Who are you the layout = azerty (ok!)

Test3 : Set keyboard-layout=azerty (English(US) removed) -> Start installer -> Set Keyboard-layout=English(US)  -> @ Who are you the layout = azerty (not ok!), should be Qwerty

**Comment by MenthaSuaveolens** [comment]
I notice the message "Preparing Ubuntu-drivers" after selecting the keyboard-layout. Is this module messing up with the selected layout?

**Comment by clefebvre** [comment]
There we go, I knew I saw this before! 

https://github.com/linuxmint/linuxmint/issues/311

**Comment by clefebvre** [comment]
Fixed in open-vm-tools.
