### ISSUE TITLE
Celluloid - when the program window is maximized, putting the cursor in very top-right corner and left-clicking doesn't select the 'close' button

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#94]
(tested with Cinnamon and Xfce on both live sessions as well as fully-updated local installations as of 2022-07-15)

**Describe the bug**
When Celluloid's program window is maximized, putting the cursor into the very top-right corner and left-clicking does not select the 'close' button.

**To Reproduce**
1. boot Mint 21 beta (whether a live session or a local installation)
2. open Celluloid
3. maximize the program window
4. put your mouse cursor in the very top-right corner
5. left click
6. ...nothing happened; the program window is still open

**Expected behavior**
When one puts the mouse pointer in the very top-right corner of a maximized window and then left-clicks, it should 'select' the "close" button.

**Additional context**
Putting the mouse pointer in the very top-right corner of a maximized window and then left-clicking closes the program window for at least Nemo, Thunar, Xed, and Firefox - why should Celluloid be any different?

**Comment by JosephMcc** [comment]
> why should Celluloid be any different?

Because Celluloid and other apps like Calculater, Mint Welcome, Calendar, etc. are client side decorated. Meaning they use header bars and  the decorations aren't drawn by muffin. Theming is different for those apps and the way header bars are themed it's not really possible to achieve that same behavior without completely breaking how they look. This isn't a bug. It's just a limitation of headerbar theming.
