### ISSUE TITLE
[Cinnamon] (Live session ONLY) Nemo - sorting file names alphabetically puts capitalized file names first (e.g. it goes "Cat, Fish, bear, dog" rather than the expected "bear, Cat, dog, Fish"

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#97]
**Describe the bug**
In _only_ a live session of Cinnamon, when sorting file names alphabetically in Nemo, it puts capitalized file names first, e.g. it goes:
- Cat
- Fish
- bear
- dog

...rather than the expected:
- bear
- Cat
- dog
- Fish

**To Reproduce**
1. boot the live ISO for Cinnamon
2. Open Nemo
3. create 4 new blank files with the following file names:
- bear
- Cat
- dog
- Fish
4. sort the files alphabetically (you may also want to close and re-open Nemo)
5. observe how the files are now listed in the following order:
- Cat
- Fish
- bear
- dog

**Expected behavior**
When file names are sorted alphabetically, they should be case-insensitive just like how they are in a live session of Xfce beta 21.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/11896003/179429948-bee3e028-e3a3-4179-b67c-9abf479821ff.png)

**Additional context**
As mentioned, this does not occur in live Xfce beta 21 nor does it occur in a local installation of Cinnamon beta 21 that has been fully updated as of 2021-07-15

**Comment by mtwebster** [comment]
This is because there's no system locale set in the live session - see:
![image](https://user-images.githubusercontent.com/262776/179432106-a559343c-a7f6-49e4-b27b-1416101d65da.png)
It's sorting by ascii value basically - caps before lower case:
![image](https://user-images.githubusercontent.com/262776/179432204-fd49303f-6bcc-4e07-bdcb-8210e23f8eca.png)

try this:
```
LC_ALL=en_US.UTF-8 nemo
```
You'll see the sort order is more sensible.

This is normal for the live cds. Not sure why sort works in xfce but I'd guess thunar (the file manager) sees that there's no locale set and uses a reasonable default (probably en_US).
